# Generated by Django 5.2.5 on 2025-09-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('manager_name', models.CharField(blank=True, max_length=255)),
                ('venue_type', models.CharField(choices=[('shopping_center', 'Shopping Center'), ('mall', 'Mall'), ('office_building', 'Office Building'), ('retail_store', 'Retail Store'), ('parking_garage', 'Parking Garage'), ('other', 'Other')], default='shopping_center', max_length=50)),
                ('capacity', models.IntegerField(blank=True, help_text='Maximum occupancy', null=True)),
                ('operating_hours', models.CharField(blank=True, help_text='e.g., Mon-Sun 9AM-9PM', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
