# Generated by Django 5.2.5 on 2025-10-02 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_offenders', '0001_initial'),
        ('a_venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('vandalism', 'Vandalism'), ('other', 'Other')], default='other', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warning', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('ban', models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20)),
                ('offender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_incidents', to='a_offenders.offender')),
                ('offenders', models.ManyToManyField(blank=True, related_name='incidents', to='a_offenders.offender')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_venues.venue')),
            ],
        ),
    ]
