# Generated by Django 5.2.5 on 2025-09-30 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0001_initial'),
        ('a_offenders', '0001_initial'),
        ('a_venues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='offender_name',
        ),
        migrations.AddField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('vandalism', 'Vandalism'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='incident',
            name='offenders',
            field=models.ManyToManyField(blank=True, related_name='incidents', to='a_offenders.offender'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='offender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_incidents', to='a_offenders.offender'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_venues.venue'),
        ),
    ]
