# Generated by Django 5.2.5 on 2025-10-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0001_initial'),
        ('a_offenders', '0002_ban_warning_incidentoffender'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium-Low'), (3, 'Medium'), (4, 'Medium-High'), (5, 'High')], default=3),
        ),
        migrations.AlterField(
            model_name='incident',
            name='offenders',
            field=models.ManyToManyField(blank=True, related_name='group_incidents', to='a_offenders.offender'),
        ),
    ]
