# Generated by Django 5.2.5 on 2025-09-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0002_incident_offender_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='venue',
            field=models.CharField(default='Mascot', max_length=255),
            preserve_default=False,
        ),
    ]
