# Generated by Django 5.2.5 on 2025-09-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0003_incident_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='warning',
            field=models.BooleanField(default=False),
        ),
    ]
