# Generated by Django 5.2.5 on 2025-09-03 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0004_incident_ban_incident_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='ban',
            field=models.CharField(choices=[('none', 'No Ban'), ('temporary', 'Temporary Ban'), ('permanent', 'Permanent Ban')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='warning',
            field=models.CharField(choices=[('none', 'No Warning'), ('verbal', 'Verbal Warning'), ('written', 'Written Warning')], default='none', max_length=20),
        ),
    ]
