# Generated by Django 5.2.5 on 2025-09-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0005_alter_incident_ban_alter_incident_warning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='ban',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='warning',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes')], default='no', max_length=20),
        ),
    ]
