# Generated by Django 5.2.5 on 2025-09-29 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0006_alter_incident_ban_alter_incident_warning'),
        ('a_offenders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='offender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='a_offenders.offender'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='offender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
