trigger:
- main

pool:
  name: "Self Hosted Alyssa"

variables:
  DJANGO_SETTINGS_MODULE: a_core.settings
  PYTHON_VERSION: "3.10"

steps:
# Use the specified Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: "$(PYTHON_VERSION)"
    architecture: "x64"

# Install uv
- script: |
    curl -LsSf https://astral.sh/uv/install.sh | sh
    export PATH="$HOME/.cargo/bin:$PATH"
  displayName: "Install uv"

# Create virtual environment and install dependencies
- script: |
    uv venv .venv
    uv run pip install --upgrade pip
    uv run pip install -r requirements.txt
  displayName: "Install dependencies"

# Run migrations
- script: |
    uv run python manage.py makemigrations --check --dry-run
    uv run python manage.py migrate
  displayName: "Run migrations"

# Django system checks
- script: |
    uv run python manage.py check
  displayName: "Django system checks"

# Run Django unit tests
- script: |
    uv run python manage.py test
  displayName: "Run tests"

# Run pytest and generate JUnit XML report
- script: |
    uv run pytest --junitxml=$(System.DefaultWorkingDirectory)/TEST-results.xml
  displayName: "Run pytest and generate report"

# Publish test results
- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-results.xml'
    testRunTitle: 'Django Unit Tests'
  condition: succeededOrFailed()
