# Generated by Django 4.2.24 on 2025-09-30 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('a_incidents', '0007_incident_offender_alter_incident_offender_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('a_offenders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('severity', models.CharField(choices=[('L', 'Low'), ('M', 'Medium'), ('H', 'High'), ('C', 'Critical')], default='M', max_length=1)),
                ('notes', models.TextField()),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warnings', to='a_incidents.incident')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='a_offenders.offender')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(max_length=300)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='a_offenders.offender')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentOffender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offender_links', to='a_incidents.incident')),
                ('offender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_links', to='a_offenders.offender')),
            ],
            options={
                'unique_together': {('offender', 'incident')},
            },
        ),
    ]
