# Generated by Django 4.2.24 on 2025-10-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_offenders', '0002_warning_ban_incidentoffender'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='incidentoffender',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='incidentoffender',
            constraint=models.UniqueConstraint(fields=('offender', 'incident'), name='uq_incidentoffender_offender_incident'),
        ),
    ]
